apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: yfo9we9ac-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/yfo9we9ac-java-springboot-gitops